site_name: My Docs
site_url: https://www.chunyi-lin.com

theme:
  font: false
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: radix-light
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: radix-dark
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/fonts.css
  - stylesheets/radix.css
  - stylesheets/header.css
  - stylesheets/footer.css

extra_javascript:
  - javascripts/footer-theme.js

extra:
  footer:
    author_name: Chunyi Lin
    years: "2026"
    license_name: CC BY 4.0
    license_url: https://creativecommons.org/licenses/by/4.0/
    repo_url: https://github.com/c-lin-chunyi/blog
    orcid: 0009-0008-9762-8705
    pgp_key: pgp_clin.asc.txt
    pgp_fingerprint: "15C2 CB51 1D1E 1A79 C2B2<br>F5F3 ED31 DE03 7AEF 5C7E"

markdown_extensions:
  - admonition
