[project]
site_name = "My Docs"
site_url = "https://www.chunyi-lin.com"
copyright = """
Copyright &copy; 2026 Chunyi Lin. Content licensed under
<a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener">CC BY 4.0</a>.
"""
repo_url = "https://github.com/c-lin-chunyi/blog"
extra_css = [
  "stylesheets/radix.css",
]

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/c-lin-chunyi/blog"
name = "Source on GitHub"

[[project.extra.social]]
icon = "fontawesome/brands/orcid"
link = "https://orcid.org/0009-0008-9762-8705"
name = "ORCID"

[[project.extra.social]]
icon = "lucide/key-round"
link = "pgp_clin.asc.txt"
name = "PGP public key"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "radix-light"
primary = "custom"
accent = "custom"
toggle.icon = "lucide/moon"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "radix-dark"
primary = "custom"
accent = "custom"
toggle.icon = "lucide/sun"
toggle.name = "Switch to light mode"

[project.markdown_extensions.admonition]
