[project]
site_name = "Chunyi Lin's Docs"
site_url = "https://docs.chunyi-lin.com"
site_author = "Chunyi Lin"
copyright = """
Copyright &copy; 2026 Chunyi Lin. Content licensed under
<a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener">CC BY 4.0</a>.
"""
extra_css = [
  "stylesheets/fonts.css",
  "stylesheets/math.css",
  "stylesheets/radix.css",
  "stylesheets/header.css",
  "stylesheets/footer.css",
]
extra_javascript = [
  "assets/vendor/mermaid/mermaid.min.js",
  "javascripts/mermaid-init.js",
  "javascripts/footer-theme.js",
  "javascripts/safari-toc-highlight.js",
]

nav = [
  { "主页" = "index.md" },
  { "量化知识" = [
    { "量化知识目录" = "quantitative/index.md" },
    { "线性代数" = [
      { "目录" = "quantitative/linear-algebra/index.md" },
      { "01" = [
        { "章节概览" = "quantitative/linear-algebra/01_/index.md" },
        { "01 " = "quantitative/linear-algebra/01_/01_.md" },
      ] },
    ] },
    { "概率论" = [
      { "目录" = "quantitative/probability/index.md" },
      { "01" = [
        { "章节概览" = "quantitative/probability/01_/index.md" },
        { "01 " = "quantitative/probability/01_/01_.md" },
      ] },
    ] },
    { "统计学" = [
      { "目录" = "quantitative/statistics/index.md" },
      { "01" = [
        { "章节概览" = "quantitative/statistics/01_/index.md" },
        { "01 " = "quantitative/statistics/01_/01_.md" },
      ] },
    ] },
    { "实验设计与统计分析" = [
      { "目录" = "quantitative/experiment-design-and-statistical-analysis/index.md" },
      { "01" = [
        { "章节概览" = "quantitative/experiment-design-and-statistical-analysis/01_/index.md" },
        { "01 " = "quantitative/experiment-design-and-statistical-analysis/01_/01_.md" },
      ] },
      { "02" = [
        { "章节概览" = "quantitative/experiment-design-and-statistical-analysis/02_/index.md" },
        { "02 " = "quantitative/experiment-design-and-statistical-analysis/02_/02_.md" },
      ] },
      { "03" = [
        { "章节概览" = "quantitative/experiment-design-and-statistical-analysis/03_/index.md" },
        { "03 " = "quantitative/experiment-design-and-statistical-analysis/03_/03_.md" },
      ] },
      { "04" = [
        { "章节概览" = "quantitative/experiment-design-and-statistical-analysis/04_/index.md" },
        { "04 " = "quantitative/experiment-design-and-statistical-analysis/04_/04_.md" },
      ] },
      { "05" = [
        { "章节概览" = "quantitative/experiment-design-and-statistical-analysis/05_/index.md" },
        { "05 " = "quantitative/experiment-design-and-statistical-analysis/05_/05_.md" },
      ] },
      { "06" = [
        { "章节概览" = "quantitative/experiment-design-and-statistical-analysis/06_/index.md" },
        { "06 " = "quantitative/experiment-design-and-statistical-analysis/06_/06_.md" },
      ] },
      { "07" = [
        { "章节概览" = "quantitative/experiment-design-and-statistical-analysis/07_/index.md" },
        { "07 " = "quantitative/experiment-design-and-statistical-analysis/07_/07_.md" },
      ] },
      { "08" = [
        { "章节概览" = "quantitative/experiment-design-and-statistical-analysis/08_/index.md" },
        { "08 " = "quantitative/experiment-design-and-statistical-analysis/08_/08_.md" },
      ] },
    ] },
  ] },
  { "质性知识" = [
    { "目录" = "qualitative/index.md" },
  ] },
  { "课业材料" = [
    { "目录" = "coursework/index.md" },
  ] },
  { "返回主网站" = "https://www.chunyi-lin.com" },
]

[project.extra.footer]
author_name = "Chunyi Lin"
years = "2026"
license_name = "CC BY 4.0"
license_url = "https://creativecommons.org/licenses/by/4.0/"
repo_url = "https://github.com/c-lin-chunyi/docs"
orcid = "0009-0008-9762-8705"
pgp_key = "pgp_clin.asc.txt"
pgp_fingerprint = "15C2 CB51 1D1E 1A79 C2B2<br>F5F3 ED31 DE03 7AEF 5C7E"

[project.theme]
language = "zh"
font = false
custom_dir = "overrides"
features = [
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  "navigation.footer",
  "navigation.indexes",
  "navigation.path",
  #  "navigation.sections",
  "navigation.top",
  "navigation.tabs",
  "navigation.tracking",
  "toc.follow",
  "search.highlight",
]
favicon = "assets/favicon.svg"
logo = "assets/logo.svg"

[[project.theme.palette]]
media = "(prefers-color-scheme)"
scheme = "radix-light"
primary = "custom"
accent = "custom"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "radix-light"
primary = "custom"
accent = "custom"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "radix-dark"
primary = "custom"
accent = "custom"

[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.toc]
permalink = true

[project.markdown_extensions.pymdownx.arithmatex]
generic = true
[project.markdown_extensions.pymdownx.betterem]
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.emoji]
emoji_generator = "zensical.extensions.emoji.to_svg"
emoji_index = "zensical.extensions.emoji.twemoji"
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.magiclink]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.smartsymbols]
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid-source", format = "pymdownx.superfences.fence_code_format" },
]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
combine_header_slug = true
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
[project.markdown_extensions.pymdownx.tilde]
